"""add geocode_precision column

Revision ID: 439d23d421d4
Revises: e1069b4588f2
Create Date: 2026-02-12 16:37:14.014348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '439d23d421d4'
down_revision = 'e1069b4588f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('geocode_precision', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.drop_column('geocode_precision')

    # ### end Alembic commands ###
